memo-app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'memos#index'
  resources :memos, only: [:create, :destroy]
end

memo-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

memo-app/app/models/memo.rb
class Memo < ApplicationRecord
end

memo-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

memo-app/app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def index
    @memos = Memo.all
    @memo = Memo.new
  end
  
  def create
    Memo.create(memo_params)
    @memos = Memo.all
  end

  def destroy
    Memo.find(params[:id]).destroy
    @memos = Memo.all
  end
  
  private
  def memo_params
    params.require(:memo).permit(:text)
  end
end

memo-app/app/helpers/application_helper.rb
module ApplicationHelper
end

memo-app/app/helpers/memos_helper.rb
module MemosHelper
end

memo-app/app/views/memos/_memo.html.erb
<li>
  <%= memo.text %>
  <%= link_to '削除', memo_path(memo), method: :delete, remote: true %>
</li>

memo-app/app/views/memos/create.js.erb
$("#memo_text").val(""); // 入力フォームを空欄にする処理
$("ul").html("<%= j(render @memos) %>");

memo-app/app/views/memos/destroy.js.erb
$("ul").html("<%= j(render @memos) %>")

memo-app/app/views/memos/index.html.erb
<%= form_for @memo, remote: true do |f| %>
  <%= f.text_field :text %>
  <%= f.submit '投稿' %>
<% end %>
<ul>
  <%= render @memos %>
</ul>