profy/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  root to: "top#index"
  resources :groups, only: [:show, :edit, :update]
  resources :questions, only: [:create, :show]
  resources :answers, only: [:new, :create, :edit, :update]
end

profy/app/models/answer.rb
class Answer < ApplicationRecord
  
  #association
  belongs_to :question
  belongs_to :user
  has_one :feed_content, as: :content, dependent: :destroy
  
  #callback
  after_create :create_feed_content
  after_update :update_feed_content
  
  #validation
  validates_presence_of :user_id, :text

  private
  def create_feed_content
    self.feed_content = FeedContent.create(group_id: question.group_id, updated_at: updated_at)
  end
  
  def update_feed_content
    self.feed_content.update(updated_at: updated_at)
  end
end

profy/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

profy/app/models/feed_content.rb
class FeedContent < ApplicationRecord
  belongs_to :content, polymorphic: true
end

profy/app/models/group.rb
class Group < ApplicationRecord
  
  #association
  has_many :users
  has_many questions, ->{ order("created_at DESC") }
  has_many :feed_contents, ->{order("update_at DESC") }
end

profy/app/models/question.rb
class Question < ApplicationRecord
  
  #association
  belongs_to :user
  belongs_to :group
  has_many :answers
  has_one :feed_content, as: :content, dependent: :destroy
  #validation
  validates_presence_of :user_id, :text, :group_id
  
  #callback
  after_create :create_feed_content
  
  def user_answer(user_id)
    Answer.find_by(user_id: user_id, question_id: id)
  end
  
  def answered?(user)
    answers.exists?(user_id)
  end
  
  private
  def create_feed_content
    self.feed_content = FeedContent.create(group_id: group_id, updated_at: updated_at)
  end
end

profy/app/models/user.rb
class User < ApplicationRecord

  has_one_attached :image
  
  #accessor
  attr_accessor :group_key

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         authentication_keys: [:email, :group_key]

  #association
  belongs_to :group
  has_many :questions, ->{ order("created_at DESC") }
  has_many :answers, ->{ order("updated_at DESC") }
  has_many :answered_questions, through: :answers, source: :question
  
  #validation
  before_validation :group_key_to_id, if: :has_group_key?

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    group_key = conditions.delete(:group_key)
    group_id = Group.where(key: group_key).first
    email = conditions.delete(:email) || conditions.delete(:unconfirmed_email)

    # devise認証を、複数項目に対応させる
    if group_id && email
      find_by(group_id: group_id, email: email)
    elsif conditions.has_key?(:confirmation_token)
      where(conditions).first
    elsif email
      where(email: email).first
    else
      false
    end
  end

  def name
    "#{family_name} #{first_name}"
  end
  
  def name_kana
    "#{family_name_kana} #{first_name_kana}"
  end
  
  def full_profile?
    image.attached?  && family_name? && first_name? && family_name_kana? && first_name_kana?
  end
  
  private
  def has_group_key?
    group_key.present?
  end

  def group_key_to_id
    group = Group.where(key: group_key).first_or_create
    self.group_id = group.id
  end
end

profy/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  before_action :redirect, only: :new
  
  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
    @answer.question_id = @question.id
    if @question.answers.exists?(user_id: current_user.id)
      redirect_to :root
    end
  end
  
  def create
    @answer = Answer.create(create_params)
  end

  def edit
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def update
    answer = Answer.find(params[:id])
    @question = answer.question
    answer.update(update_params)
  end
  
  private
  def create_params
    params.require(:answer).permit(:question_id, :text).merge(user_id: current_user.id)
  end
  
  def redirect
    if Answer.exists?(question_id: params[:question_id], user_id: current_user.id)
      redirect_to :root
    end
  end
  
  def update_params
    params.require(:answer).permit(:text)
  end
end

profy/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def configure_permitted_parameters
    # sign_inのときに、group_keyも許可する
      devise_parameter_sanitizer.permit(:sign_in, keys:[:group_key])
    # sign_upのときに、group_keyも許可する
      devise_parameter_sanitizer.permit(:sign_up, keys:[:group_key])
    #account_updateのときに、group_keyも許可する
      devise_parameter_sanitizer.permit(:account_update, keys:[:group_key])
  end
end

profy/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  def show
    @group = Group.find(params[:id])
  end
  
  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(update_params)
  end

  private
  def update_params
    params.require(:group).permit(:key, :detail)
  end
end

profy/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def create
    Question.create(create_params)
    redirect_to :root and return
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
  end
  
  private
  def create_params
    params.require(:question).permit(:text).merge(user_id: current_user.id, group_id: current_user.group_id)
  end
end

profy/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @question = Question.new
    @feed_contents = current_user.group.feed_contents.includes(:content).page(params[:page]).per(5)
    @feed_contents_resource = @feed_contents.map(&:content)
  end
end

profy/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @questions = @user.answerer_questions.uniq
  end
  
  def edit
  end
  
  def update
    current_user.update(update_params)
  end
  
  private
  def update_params
    params.require(:user).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :image)
  end
end

profy/app/helpers/answers_helper.rb
module AnswersHelper
end

profy/app/helpers/application_helper.rb
module ApplicationHelper
end

profy/app/helpers/groups_helper.rb
module GroupsHelper
end

profy/app/helpers/questions_helper.rb
module QuestionsHelper
end

profy/app/helpers/top_helper.rb
module TopHelper
end

profy/app/helpers/users_helper.rb
module UsersHelper
end

profy/app/views/questions/_answer.html.erb
<section class="col-md-12">
  <div class="sct_inner">
    <p><%= link_to answer.user.name, user_path(answer.user) %>さんの回答</p>
    <h4>→<%= answer.text %></h4>
  </div>
</section>

profy/app/views/questions/_question.html.erb
<div class="question_content top_content">
  <header class="question_header">
    <div class="question_image icon_image" style="background-image: url(<%= rails_blob_path( question.user.image) %>);"></div>
    <div class="question_user_info user_info">
      <span><%= link_to question.user.name, user_path(question.user) %></span>
      <time><%= time_ago_in_words question.created_at %></time>
    </div>
  </header>
  <div class="question_body">
    <div class="question_box">
      <span class="q">Q</span>
      <span class="question_text"><%= question.text %></span>
    </div>
    <div class="questioned">
      <%= link_to "回答#{question.answers.count}件", question_path(question) %>
    </div>
    <% unless question.answers.exists?(user_id: current_user.id) %>
      <%= form_tag(new_answer_path, method: :get, class: "question_submit") do %>
        <%= hidden_field_tag(:question_id, question.id) %>
        <%= submit_tag("回答する") %>
      <% end %>
    <% else %>
      <div class='answer_other'>
        <h4>※回答済み※</h4>
      </div>
    <% end %>
  </div>
</div>

profy/app/views/questions/show.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3><span>Q</span><%= @question.text %></h3>
    <div class="group_action panel panel-default">
      <div class="panel-body">
        <% unless @question.answers.exists?(user_id: current_user.id) %>
          <%= link_to '質問に回答する', new_answer_path(question_id: @question.id) %>
        <% else %>
          <h4>※回答済み※</h4>
        <% end %>
      </div>
    </div>
    <% if @question.answers.present? %>
      <h3><span>A</span>この質問への回答</h3>
      <% if @question.answered?(current_user) %>
      <%= render partial: "questions/answer", collection: @answers %>
      <% else %>
        <h1>※質問に答えると他の人の回答を見ることが出来ます</h1>
      <% end %>
    <% end %>
  </div>
</div>

profy/app/views/users/_question.html.erb
<div class="question_content top_content">
  <div class="question_body">
    <div class="question_box">
      <span class="q">Q</span>
      <span class="question_text"><%= question.text %></span>
    </div>
    <div class="answer_box" style="margin-bottom: 10px;">
      <span class="a">A</span>
      <span class="answer_text"><%= question.user_answer(@user.id).text %></span>
      <% if @user.id == current_user.id %>
        <small class='edit'>
          <%= link_to '編集', edit_answer_path(question.user_answer(@user.id)) %>
        </small>
      <% end %>
    </div>
  </div>
</div>

profy/app/views/users/edit.html.erb
<%provide :title, " | プロフィール編集" %>

<div class="row form">
  <div class="col-lg-12">
    <%= form_for current_user do |f| %>
      <h2>プロフィール画像</h2>
      <div class="form-group file">
        <%= f.file_field :image, class: "form-control floating-label", placeholder: "画像アップロード" %>
      </div>
      <h2>登録情報</h2>
      <div class="form-group">
        <div class="col-lg-6">
          <%= f.text_field :family_name, placeholder: "姓", class: "form-control" %>
        </div>
        <div class="col-lg-6">
          <%= f.text_field :first_name, placeholder: "名", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-6">
          <%= f.text_field :family_name_kana, placeholder: "セイ", class: "form-control" %>
        </div>
        <div class="col-lg-6">
          <%= f.text_field :first_name_kana, placeholder: "メイ", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "送信", class: "btn btn-primary withripple" %>
      </div>
    <% end %>
  </div>
</div>

profy/app/views/users/show.html.erb
<% provide :title, " | #{@user.name}さん" %>

<div class="row form user_profile">
  <div class="col-lg-12">
    <div class="image" style="background-image: url(<%= rails_blob_path(@user.image) %>) "></div>
    <h2><%= @user.name %><span><%= @user.name_kana %></span></h2>
    <% if current_user.id == @user.id %>
      <div class="profile_edit">
        <%= link_to "プロフィール編集", edit_user_path(current_user), {:class => "btn btn-primary withripple" }%>
      </div>
    <% end %>
    
    <% if @questions.present? %>
      <h3>このユーザーの回答した質問</h3>
      <div class='clearfix'>
        <%= render partial: 'users/question', collection: @questions %>
      </div>
    <% end %>
  </div>
</div>

profy/app/views/users/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>プロフィールの編集が完了しました。</h3>
    <%= link_to "ホームに戻る", root_path %>
  </div>
</div>